const projects = [
  // ── Tools ────────────────────────────────────────────────────
  {
    id: "age-calculator",
    name: "Age Calculator",
    category: "tools",
    description:
      "Calculate your exact age in years, months, and days from your birthdate.",
    tags: ["age", "date", "birthday", "calculator"],
    added: "2026-06-07",
    thumbnail: null,
    icon: "fa-solid fa-cake-candles",
  },
  {
    id: "calculator",
    name: "Calculator",
    category: "tools",
    description: "Arithmetic calculator with keyboard input support.",
    tags: ["math", "arithmetic", "keyboard"],
    added: "2026-06-07",
    thumbnail: null,
    icon: "fa-solid fa-calculator",
  },
  {
    id: "random-password-generator",
    name: "Password Generator",
    category: "tools",
    description:
      "Generate secure passwords with custom length and character sets.",
    tags: ["password", "security", "random", "generator"],
    added: "2026-06-07",
    thumbnail: null,
    icon: "fa-solid fa-key",
  },
  {
    id: "temperature-converter",
    name: "Temperature Converter",
    category: "tools",
    description:
      "Real-time conversion between Celsius, Fahrenheit, and Kelvin.",
    tags: ["temperature", "convert", "celsius", "fahrenheit", "kelvin"],
    added: "2026-06-07",
    thumbnail: null,
    icon: "fa-solid fa-temperature-half",
  },
  {
    id: "word-counter",
    name: "Word Counter",
    category: "tools",
    description:
      "Count words, characters, sentences, and estimated reading time.",
    tags: ["text", "words", "count", "reading"],
    added: "2026-06-07",
    thumbnail: null,
    icon: "fa-solid fa-font",
  },
  {
    id: "color-picker",
    name: "Color Picker",
    category: "tools",
    description:
      "Pick a color and copy its HEX, RGB, or HSL value to clipboard.",
    tags: ["color", "hex", "rgb", "hsl", "clipboard", "design"],
    added: "2026-06-08",
    thumbnail: null,
    icon: "fa-solid fa-palette",
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    category: "tools",
    description: "Convert length, weight, and volume units with live updates.",
    tags: ["units", "convert", "length", "weight", "volume"],
    added: "2026-06-08",
    thumbnail: null,
    icon: "fa-solid fa-arrows-left-right",
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    category: "tools",
    description:
      "Paste JSON to prettify or minify it, with syntax error highlighting.",
    tags: ["json", "format", "prettify", "minify", "developer"],
    added: "2026-06-08",
    thumbnail: null,
    icon: "fa-solid fa-code",
  },
  {
    id: "tip-calculator",
    name: "Tip Calculator",
    category: "tools",
    description:
      "Split the bill with custom tip percentages and per-person breakdown.",
    tags: ["tip", "bill", "split", "restaurant", "calculator"],
    added: "2026-06-08",
    thumbnail: null,
    icon: "fa-solid fa-receipt",
  },
  {
    id: "loan-calculator",
    name: "Loan Calculator",
    category: "tools",
    description:
      "Calculate monthly payments, total cost, and interest for any loan.",
    tags: ["loan", "mortgage", "interest", "finance", "calculator"],
    added: "2026-06-08",
    thumbnail: null,
    icon: "fa-solid fa-hand-holding-dollar",
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    category: "tools",
    description:
      "Calculate your Body Mass Index with metric or imperial inputs and health category.",
    tags: ["bmi", "health", "weight", "height", "calculator"],
    added: "2026-06-11",
    thumbnail: null,
    icon: "fa-solid fa-weight-scale",
  },
  {
    id: "currency-converter",
    name: "Currency Converter",
    category: "tools",
    description:
      "Convert between 20 major currencies using fixed reference exchange rates.",
    tags: ["currency", "convert", "exchange", "money", "finance"],
    added: "2026-06-11",
    thumbnail: null,
    icon: "fa-solid fa-coins",
  },
  {
    id: "roman-numeral-converter",
    name: "Roman Numeral Converter",
    category: "tools",
    description:
      "Bidirectional converter between Arabic numbers (1–3999) and Roman numerals.",
    tags: ["roman", "numeral", "convert", "history", "math"],
    added: "2026-06-11",
    thumbnail: null,
    icon: "fa-solid fa-roman",
  },
  {
    id: "text-to-morse",
    name: "Text to Morse",
    category: "tools",
    description:
      "Convert text to Morse code and back. Play the encoded message as audio beeps.",
    tags: ["morse", "code", "encode", "decode", "audio"],
    added: "2026-06-11",
    thumbnail: null,
    icon: "fa-solid fa-signal",
  },
  {
    id: "css-gradient-generator",
    name: "CSS Gradient Generator",
    category: "tools",
    description:
      "Build linear, radial, or conic gradients with custom stops and copy the CSS.",
    tags: ["css", "gradient", "color", "design", "generator"],
    added: "2026-06-11",
    thumbnail: null,
    icon: "fa-solid fa-swatchbook",
  },
  {
    id: "readability-score",
    name: "Readability Score",
    category: "tools",
    description:
      "Analyze text using the Flesch Reading Ease formula and get grade-level feedback.",
    tags: ["readability", "text", "analysis", "flesch", "writing"],
    added: "2026-06-11",
    thumbnail: null,
    icon: "fa-solid fa-book-open",
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder",
    category: "tools",
    description:
      "Encode and decode Base64 strings with a single click and copy support.",
    tags: ["base64", "encode", "decode", "developer", "binary"],
    added: "2026-06-13",
    thumbnail: null,
    icon: "fa-solid fa-binary",
  },
  {
    id: "text-case-converter",
    name: "Case Converter",
    category: "tools",
    description:
      "Convert text between camelCase, snake_case, PascalCase, kebab-case, and more.",
    tags: ["text", "case", "convert", "camel", "snake", "developer"],
    added: "2026-06-13",
    thumbnail: null,
    icon: "fa-solid fa-text-height",
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    category: "tools",
    description:
      "Test regular expressions with live match highlighting and match list.",
    tags: ["regex", "regexp", "pattern", "test", "developer"],
    added: "2026-06-13",
    thumbnail: null,
    icon: "fa-solid fa-magnifying-glass-plus",
  },
  {
    id: "markdown-previewer",
    name: "Markdown Previewer",
    category: "tools",
    description:
      "Write Markdown on the left, see the live HTML preview on the right.",
    tags: ["markdown", "preview", "html", "editor", "developer"],
    added: "2026-06-13",
    thumbnail: null,
    icon: "fa-brands fa-markdown",
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    category: "tools",
    description:
      "Generate SHA-256, SHA-1, or SHA-512 hashes from any text using the Web Crypto API.",
    tags: ["hash", "sha", "crypto", "security", "developer"],
    added: "2026-06-13",
    thumbnail: null,
    icon: "fa-solid fa-fingerprint",
  },

  // ── Games ────────────────────────────────────────────────────
  {
    id: "rock-paper-scissors",
    name: "Rock Paper Scissors",
    category: "games",
    description: "Classic hand game against the computer with score tracking.",
    tags: ["game", "random", "score", "classic"],
    added: "2026-06-09",
    thumbnail: null,
    icon: "fa-solid fa-hand-scissors",
  },
  {
    id: "number-guessing-game",
    name: "Number Guessing",
    category: "games",
    description:
      "Guess the secret number with higher/lower hints and attempt counter.",
    tags: ["game", "guess", "number", "random"],
    added: "2026-06-09",
    thumbnail: null,
    icon: "fa-solid fa-dice",
  },
  {
    id: "memory-card-game",
    name: "Memory Cards",
    category: "games",
    description: "Flip cards to find matching pairs. Track time and moves.",
    tags: ["game", "memory", "cards", "pairs", "match"],
    added: "2026-06-09",
    thumbnail: null,
    icon: "fa-solid fa-clone",
  },
  {
    id: "typing-speed-test",
    name: "Typing Speed Test",
    category: "games",
    description: "Measure your WPM and accuracy against a random paragraph.",
    tags: ["game", "typing", "wpm", "accuracy", "speed"],
    added: "2026-06-09",
    thumbnail: null,
    icon: "fa-solid fa-keyboard",
  },
  {
    id: "whack-a-mole",
    name: "Whack-a-Mole",
    category: "games",
    description: "Click the moles before they disappear! Timed arcade fun.",
    tags: ["game", "arcade", "click", "timer", "score"],
    added: "2026-06-09",
    thumbnail: null,
    icon: "fa-solid fa-hammer",
  },
  {
    id: "snake-game",
    name: "Snake Game",
    category: "games",
    description: "Classic snake on an HTML5 Canvas. Eat, grow, don't crash.",
    tags: ["game", "snake", "canvas", "classic", "keyboard"],
    added: "2026-06-10",
    thumbnail: null,
    icon: "fa-solid fa-worm",
  },
  {
    id: "quiz-app",
    name: "Quiz App",
    category: "games",
    description: "Multiple-choice trivia quiz with a score summary and timer.",
    tags: ["game", "quiz", "trivia", "score", "timer"],
    added: "2026-06-10",
    thumbnail: null,
    icon: "fa-solid fa-circle-question",
  },
  {
    id: "tic-tac-toe",
    name: "Tic-Tac-Toe",
    category: "games",
    description: "Classic 3×3 grid game against an unbeatable minimax AI.",
    tags: ["game", "tic-tac-toe", "ai", "classic", "strategy"],
    added: "2026-06-10",
    thumbnail: null,
    icon: "fa-solid fa-xmark",
  },
  // ── UI Components ────────────────────────────────────────────
  {
    id: "digital-clock",
    name: "Digital Clock",
    category: "ui",
    description:
      "Live digital clock showing hours, minutes, seconds, and AM/PM.",
    tags: ["clock", "time", "real-time", "display"],
    added: "2026-04-18",
    thumbnail: null,
    icon: "fa-solid fa-clock",
  },
  {
    id: "stopwatch",
    name: "Stopwatch",
    category: "ui",
    description:
      "Start, stop, lap, and reset with a precision formatted display.",
    tags: ["timer", "stopwatch", "lap", "time"],
    added: "2026-04-18",
    thumbnail: null,
    icon: "fa-solid fa-stopwatch",
  },
  {
    id: "accordion-menu",
    name: "Accordion",
    category: "ui",
    description: "Animated expand/collapse FAQ-style accordion component.",
    tags: ["accordion", "faq", "collapse", "animation", "ui"],
    added: "2026-04-18",
    thumbnail: null,
    icon: "fa-solid fa-bars-staggered",
  },
  // ── Visualizers ──────────────────────────────────────────────────
];

export default projects;
